server:
  port: 1111   # HTTP port
  
# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
 # Averiguar para que sirve eureka.server.enableselfPreservation.

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
